"""
Django settings for djangonexia project.

Generated by 'django-admin startproject' using Django 5.2.14.
"""

import os
from pathlib import Path
import dj_database_url

# 1. BASE_DIR siempre debe ir primero para que los demás puedan usarlo
BASE_DIR = Path(__file__).resolve().parent.parent

# QUICK-START DEVELOPMENT SETTINGS - UNSUITABLE FOR PRODUCTION
# Clave corregida sin caracteres de escape conflictivos
SECRET_KEY = 'django-insecure-n3x1a_l4bs_s3cur3_k3y_production_2026_ok_987654321'

DEBUG = False

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',  # Tu app local
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Integrado correctamente aquí para Render
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'djangonexia.urls'

# Se unificaron los dos bloques de TEMPLATES en uno solo con tu ruta personalizada
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'djangonexia.wsgi.application'


# Database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'

# Carpetas de origen (Donde pones tus imágenes como logo2.svg)
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

# Destino de recolección para producción en Render
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Forzar a WhiteNoise a buscar archivos indexados en la raíz si es necesario
WHITENOISE_INDEX_FILE = True

# Configuración dinámica para evitar errores 404 en desarrollo local y optimizar en Render
if DEBUG:
    STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email Configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'nexia.labs1@gmail.com'
EMAIL_HOST_PASSWORD = 'vgal dpwc orhy igdq'